### ISSUE TITLE
main.jsがどこにあるかわからない

### ISSUE THREAD

**Issue by YuminosukeSato** [shivase/obsidian-textlint#13]
main.jsがこのリポジトリの中にありません。
どこにあるでしょうか？

**Comment by sumik5** [comment]
src/index.ts にありますが、これがgithub actionでbuildされてindex.jsに変換され、それがpackage化されてrelease物になります。

これはBugとかでは無いので、IssuesではなくDiscussionsが適切かと思います。クローズ致しますね
